-- Widget Custom Data
return {
	version = 9,
	["Auto Group"] = {
		version = "3.031",
		groups = {
			[1] = {
				[1] = "jumpskirm",
				[2] = 7,
			},
			[2] = {
				[1] = "shieldcon",
				[2] = 0,
			},
			[3] = {
				[1] = "jumpaa",
				[2] = 5,
			},
			[4] = {
				[1] = "shieldarty",
				[2] = 7,
			},
		},
	},
	["Auto Group 4"] = {
		version = "4",
		groups = {
			[1] = {
				[1] = "amphassault",
				[2] = 7,
			},
			[2] = {
				[1] = "amphcon",
				[2] = 0,
			},
			[3] = {
				[1] = "amphfloater",
				[2] = 9,
			},
			[4] = {
				[1] = "amphimpulse",
				[2] = 1,
			},
			[5] = {
				[1] = "amphlaunch",
				[2] = 4,
			},
			[6] = {
				[1] = "amphraid",
				[2] = 1,
			},
			[7] = {
				[1] = "shieldbomb",
				[2] = 8,
			},
			[8] = {
				[1] = "hoverassault",
				[2] = 7,
			},
			[9] = {
				[1] = "shieldcon",
				[2] = 0,
			},
			[10] = {
				[1] = "hovercon",
				[2] = 0,
			},
			[11] = {
				[1] = "shieldfelon",
				[2] = 9,
			},
			[12] = {
				[1] = "hoverdepthcharge",
				[2] = 7,
			},
			[13] = {
				[1] = "shieldraid",
				[2] = 1,
			},
			[14] = {
				[1] = "hoverheavyraid",
				[2] = 1,
			},
			[15] = {
				[1] = "shieldriot",
				[2] = 4,
			},
			[16] = {
				[1] = "shieldscout",
				[2] = 2,
			},
			[17] = {
				[1] = "hoverraid",
				[2] = 1,
			},
			[18] = {
				[1] = "hoverriot",
				[2] = 4,
			},
			[19] = {
				[1] = "shieldskirm",
				[2] = 7,
			},
			[20] = {
				[1] = "shipaa",
				[2] = 5,
			},
			[21] = {
				[1] = "hoverskirm",
				[2] = 3,
			},
			[22] = {
				[1] = "shiparty",
				[2] = 7,
			},
			[23] = {
				[1] = "bomberheavy",
				[2] = 9,
			},
			[24] = {
				[1] = "shipassault",
				[2] = 4,
			},
			[25] = {
				[1] = "jumpaa",
				[2] = 5,
			},
			[26] = {
				[1] = "shipcon",
				[2] = 0,
			},
			[27] = {
				[1] = "jumparty",
				[2] = 7,
			},
			[28] = {
				[1] = "jumpassault",
				[2] = 7,
			},
			[29] = {
				[1] = "shipriot",
				[2] = 1,
			},
			[30] = {
				[1] = "jumpblackhole",
				[2] = 4,
			},
			[31] = {
				[1] = "shipscout",
				[2] = 1,
			},
			[32] = {
				[1] = "jumpbomb",
				[2] = 9,
			},
			[33] = {
				[1] = "shipskirm",
				[2] = 1,
			},
			[34] = {
				[1] = "jumpcon",
				[2] = 0,
			},
			[35] = {
				[1] = "shiptorpraider",
				[2] = 9,
			},
			[36] = {
				[1] = "jumpraid",
				[2] = 1,
			},
			[37] = {
				[1] = "spideraa",
				[2] = 5,
			},
			[38] = {
				[1] = "spiderantiheavy",
				[2] = 9,
			},
			[39] = {
				[1] = "spiderassault",
				[2] = 7,
			},
			[40] = {
				[1] = "spidercon",
				[2] = 0,
			},
			[41] = {
				[1] = "spideremp",
				[2] = 4,
			},
			[42] = {
				[1] = "spiderriot",
				[2] = 4,
			},
			[43] = {
				[1] = "spiderscout",
				[2] = 2,
			},
			[44] = {
				[1] = "spiderskirm",
				[2] = 3,
			},
			[45] = {
				[1] = "cloakheavyraid",
				[2] = 9,
			},
			[46] = {
				[1] = "planecon",
				[2] = 0,
			},
			[47] = {
				[1] = "planefighter",
				[2] = 1,
			},
			[48] = {
				[1] = "planeheavyfighter",
				[2] = 5,
			},
			[49] = {
				[1] = "cloakjammer",
				[2] = 7,
			},
			[50] = {
				[1] = "planelightscout",
				[2] = 2,
			},
			[51] = {
				[1] = "striderarty",
				[2] = 9,
			},
			[52] = {
				[1] = "cloakraid",
				[2] = 1,
			},
			[53] = {
				[1] = "striderdante",
				[2] = 9,
			},
			[54] = {
				[1] = "subraider",
				[2] = 1,
			},
			[55] = {
				[1] = "cloakriot",
				[2] = 4,
			},
			[56] = {
				[1] = "tacnuke",
				[2] = 9,
			},
			[57] = {
				[1] = "tankarty",
				[2] = 7,
			},
			[58] = {
				[1] = "amphriot",
				[2] = 4,
			},
			[59] = {
				[1] = "tankcon",
				[2] = 0,
			},
			[60] = {
				[1] = "tankheavyraid",
				[2] = 1,
			},
			[61] = {
				[1] = "tankraid",
				[2] = 1,
			},
			[62] = {
				[1] = "tankriot",
				[2] = 4,
			},
			[63] = {
				[1] = "bomberriot",
				[2] = 4,
			},
			[64] = {
				[1] = "cloaksnipe",
				[2] = 7,
			},
			[65] = {
				[1] = "jumpscout",
				[2] = 2,
			},
			[66] = {
				[1] = "tankassault",
				[2] = 5,
			},
			[67] = {
				[1] = "cloakassault",
				[2] = 7,
			},
			[68] = {
				[1] = "cloakskirm",
				[2] = 3,
			},
			[69] = {
				[1] = "cloakcon",
				[2] = 0,
			},
			[70] = {
				[1] = "cloakbomb",
				[2] = 8,
			},
			[71] = {
				[1] = "gunshipaa",
				[2] = 5,
			},
			[72] = {
				[1] = "gunshipbomb",
				[2] = 8,
			},
			[73] = {
				[1] = "gunshipcon",
				[2] = 0,
			},
			[74] = {
				[1] = "athena",
				[2] = 8,
			},
			[75] = {
				[1] = "vehaa",
				[2] = 5,
			},
			[76] = {
				[1] = "veharty",
				[2] = 5,
			},
			[77] = {
				[1] = "vehassault",
				[2] = 7,
			},
			[78] = {
				[1] = "vehcapture",
				[2] = 4,
			},
			[79] = {
				[1] = "vehcon",
				[2] = 0,
			},
			[80] = {
				[1] = "vehheavyarty",
				[2] = 7,
			},
			[81] = {
				[1] = "vehraid",
				[2] = 1,
			},
			[82] = {
				[1] = "vehriot",
				[2] = 4,
			},
			[83] = {
				[1] = "gunshipemp",
				[2] = 1,
			},
			[84] = {
				[1] = "vehsupport",
				[2] = 9,
			},
			[85] = {
				[1] = "gunshipheavyskirm",
				[2] = 9,
			},
			[86] = {
				[1] = "gunshipheavytrans",
				[2] = 9,
			},
			[87] = {
				[1] = "bomberdisarm",
				[2] = 6,
			},
			[88] = {
				[1] = "jumpskirm",
				[2] = 3,
			},
			[89] = {
				[1] = "cloakarty",
				[2] = 3,
			},
			[90] = {
				[1] = "vehscout",
				[2] = 2,
			},
			[91] = {
				[1] = "gunshipraid",
				[2] = 1,
			},
			[92] = {
				[1] = "cloakaa",
				[2] = 5,
			},
			[93] = {
				[1] = "gunshipskirm",
				[2] = 3,
			},
			[94] = {
				[1] = "shieldaa",
				[2] = 5,
			},
			[95] = {
				[1] = "gunshiptrans",
				[2] = 6,
			},
			[96] = {
				[1] = "shieldarty",
				[2] = 6,
			},
			[97] = {
				[1] = "hoveraa",
				[2] = 5,
			},
			[98] = {
				[1] = "shieldassault",
				[2] = 7,
			},
			[99] = {
				[1] = "hoverarty",
				[2] = 9,
			},
			[100] = {
				[1] = "bomberprec",
				[2] = 7,
			},
		},
	},
	["Bloom Shader"] = {
		basicAlpha = 0.40000001,
		drawHighlights = false,
	},
	["Chili Docking"] = {
		Chat = {
			[1] = 515,
			[2] = -174,
			[3] = 1166,
			[4] = 29,
		},
		CommanderUpgradeWindow = {
			[1] = 517,
			[2] = -574,
			[3] = 718,
			[4] = -242,
		},
		DefenseRangesWindow = {
			[1] = 50,
			[2] = 150,
			[3] = 170,
			[4] = 318,
		},
		EconomyPanelDefaultTwo = {
			[1] = -1401,
			[2] = 0,
			[3] = -514,
			[4] = 117,
			[5] = true,
		},
		["Key Display"] = {
			[1] = 0,
			[2] = -311,
			[3] = 380,
			[4] = -247,
		},
		["Minimap Window"] = {
			[1] = 0,
			[2] = -450,
			[3] = 537,
			[4] = -17,
			[6] = true,
		},
		ModuleSelectionWindow = {
			[1] = -216,
			[2] = -538,
			[3] = -41,
			[4] = -308,
		},
		["Mouse Display"] = {
			[1] = 60,
			[2] = -375,
			[3] = 320,
			[4] = -311,
		},
		["Player List"] = {
			[1] = -322,
			[2] = 230,
			[3] = 0,
			[4] = 841,
			[5] = true,
		},
		["Player List Old"] = {
			[1] = -150,
			[2] = -121,
			[3] = 160,
			[4] = 29,
		},
		ProChat = {
			[1] = 539,
			[2] = -287,
			[3] = 1223,
			[4] = -32.549927,
			[6] = true,
		},
		ProConsole = {
			[1] = -688,
			[2] = -210,
			[3] = -12,
			[4] = 0,
			[5] = true,
			[6] = true,
		},
		ResourceBars = {
			[1] = 515,
			[2] = 0,
			[3] = 1319,
			[4] = 50,
		},
		SpaceWaster_1 = {
			[1] = 0,
			[2] = 0,
			[3] = 400,
			[4] = 300,
		},
		SpectatorEconomyPanel_vz_1 = {
			[1] = 485,
			[2] = 57,
			[3] = 965,
			[4] = 119,
		},
		SpectatorEconomyPanel_vz_2 = {
			[1] = -818,
			[2] = 56,
			[3] = -338,
			[4] = 118,
			[5] = true,
		},
		SpectatorPlayerPanel = {
			[1] = -1219,
			[2] = 0,
			[3] = -559,
			[4] = 55,
			[5] = true,
		},
		chickenpanel = {
			[1] = -110,
			[2] = -207,
			[3] = 160,
			[4] = -18,
		},
		epicmenubar = {
			[1] = -448,
			[2] = 0,
			[3] = 0,
			[4] = 38,
			[5] = true,
		},
		facbar = {
			[1] = 0,
			[2] = 9.86669922,
			[3] = 517,
			[4] = 215.866699,
		},
		facpanel = {
			[1] = 0,
			[2] = 0,
			[3] = 441,
			[4] = 270,
		},
		globalCommandsWindow = {
			[1] = -121,
			[2] = 39,
			[3] = 160,
			[4] = 71,
		},
		integralwindow = {
			[1] = 0,
			[2] = 409,
			[3] = 538,
			[4] = 624,
		},
		keyboardmenu = {
			[1] = 200,
			[2] = 300,
			[3] = 627.428589,
			[4] = 520,
		},
		mission_galaxy_objectives_4 = {
			[1] = -160,
			[2] = 83,
			[3] = 160,
			[4] = 274,
		},
		msgPersistentWindow = {
			[1] = 96,
			[2] = 248,
			[3] = 456,
			[4] = 408,
		},
		news_ticker_window = {
			[1] = 541,
			[2] = -27,
			[3] = 1226,
			[4] = 0,
			[6] = true,
		},
		objectivesButtonWindow = {
			[1] = 0,
			[2] = 32,
			[3] = 64,
			[4] = 96,
		},
		rejoinProgress = {
			[1] = 0,
			[2] = 381.090912,
			[3] = 280,
			[4] = 441.090912,
		},
		selections = {
			[1] = 0,
			[2] = 155,
			[3] = 537,
			[4] = 400.450012,
		},
		selector_window = {
			[1] = 0,
			[2] = 90,
			[3] = 373,
			[4] = 150,
		},
		uitutorial_nextButtonWindow = {
			[1] = 80,
			[2] = 508,
			[3] = 160,
			[4] = 556,
		},
		votes = {
			[1] = 2,
			[2] = 0,
			[3] = 302,
			[4] = 120,
		},
		window0 = {
			[1] = 90,
			[2] = -456,
			[3] = 300,
			[4] = -344,
		},
		window2 = {
			[1] = 50,
			[2] = -451,
			[3] = 260,
			[4] = -339,
		},
	},
	CustomFormations2 = {
		maxHungarianUnits = 66,
	},
	["EPIC Menu"] = {
		["epic_Settings/Misc_Show_Advanced_Settings"] = true,
		lang = "en",
		menuClassname = "panel_0011_small",
		music_volume = 0.02,
		showAdvanced = true,
		show_crudemenu = true,
		simpleSettingsMode = false,
		sub_pos_x = 1340,
		sub_pos_y = 253,
		subwindow_height = 620,
		versionmin = 51,
		config = {
			["epic_Area-reclaim_trees_defaultAvoidTrees"] = false,
			epic_Attrition_Counter_updateFrequency = 10,
			["epic_Auto-toggle_false_color_vision_engineheightview"] = false,
			["epic_Auto-toggle_false_color_vision_enginemetalview"] = false,
			["epic_Auto-toggle_false_color_vision_enginepathview"] = false,
			epic_AutoLLT_auto_add = false,
			epic_Auto_Group_4_addall = true,
			epic_Auto_Group_4_immediate = true,
			epic_CaretakerRefresher_updateRate = 410,
			epic_Chili_Core_Selector_background_opacity = 1,
			epic_Chili_Core_Selector_buttonSizeLong = 48,
			epic_Chili_Core_Selector_buttonSpacing = 4,
			epic_Chili_Core_Selector_fancySkinning = "panel_0110_small",
			epic_Chili_Core_Selector_horPaddingLeft = 14,
			epic_Chili_Core_Selector_horPaddingRight = 4,
			epic_Chili_Core_Selector_leftMouseCenter = true,
			epic_Chili_Core_Selector_leftsideofscreen = false,
			epic_Chili_Core_Selector_minButtonSpaces = 4,
			epic_Chili_Core_Selector_monitorInbuiltCons = true,
			epic_Chili_Core_Selector_showCoreSelector = "always",
			epic_Chili_Core_Selector_specSpaceOverride = 186,
			epic_Chili_Core_Selector_vertPadding = 9,
			epic_Chili_Core_Selector_vertical = false,
			epic_Chili_Crude_Player_List_alignToTop = true,
			epic_Chili_Crude_Player_List_backgroundOpacity = 0,
			epic_Chili_Crude_Player_List_text_height = 14,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_alignToLeft"] = false,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_alignToTop"] = true,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_backgroundOpacity"] = 0,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_colorResourceStats"] = true,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_list_size"] = 4,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_mousewheel"] = false,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_showSummaries"] = false,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_show_ccr"] = true,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_show_cpu_ping"] = false,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_show_stats"] = false,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_show_tooltips"] = true,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_stats_width"] = 3,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_text_height"] = 12,
			["epic_Chili_Deluxe_Player_List_-_Alpha_2.02_win_show_condition"] = "whenRelevant",
			epic_Chili_Docking_dockEnabledPanels = false,
			epic_Chili_Economy_Panel_Default_ecoPanelHideSpec = false,
			epic_Chili_Economy_Panel_Default_fancySkinning = "panel_2011",
			epic_Chili_Economy_Panel_Default_flowAsArrows = true,
			epic_Chili_Economy_Panel_Default_opacity = 0.94999999,
			epic_Chili_Economy_Panel_Default_warningFontSize = 8,
			epic_Chili_FactoryBar_buttonsize = 45,
			epic_Chili_FactoryPanel_showAllPlayers = false,
			epic_Chili_Global_Commands_background_opacity = 0.37,
			epic_Chili_Global_Commands_fancySkinning = "panel_1001_small",
			epic_Chili_Integral_Menu_background_opacity = 1,
			epic_Chili_Integral_Menu_fancySkinning = true,
			epic_Chili_Integral_Menu_flushLeft = true,
			epic_Chili_Integral_Menu_hide_when_spectating = false,
			epic_Chili_Integral_Menu_keyboardType2 = "custom",
			epic_Chili_Integral_Menu_leftPadding = 8,
			epic_Chili_Integral_Menu_rightPadding = 10,
			epic_Chili_Integral_Menu_selectionClosesTab = true,
			epic_Chili_Integral_Menu_selectionClosesTabOnSelect = true,
			epic_Chili_Integral_Menu_tabFontSize = 14,
			epic_Chili_Minimap_alwaysResizable = false,
			epic_Chili_Minimap_buttonsOnRight = false,
			epic_Chili_Minimap_fancySkinning = "panel_1100_large",
			epic_Chili_Minimap_hideOnOverview = false,
			epic_Chili_Minimap_hidebuttons = true,
			epic_Chili_Minimap_minimizable = false,
			epic_Chili_Minimap_opacity = 1,
			epic_Chili_Minimap_radar_fog_brightness1 = 0.5,
			epic_Chili_Minimap_use_map_ratio = "armap",
			epic_Chili_Pro_Console2_changeFont = true,
			epic_Chili_Pro_Console2_defaultBacklogEnabled = false,
			epic_Chili_Pro_Console2_enableChatBackground = false,
			epic_Chili_Pro_Console2_enableConsole = true,
			epic_Chili_Pro_Console2_error_opengl_source = true,
			epic_Chili_Pro_Console2_hideAlly = false,
			epic_Chili_Pro_Console_autohide_text_time = 25,
			epic_Chili_Pro_Console_backchatOpacity = 0,
			epic_Chili_Pro_Console_backlogHideNotChat = true,
			epic_Chili_Pro_Console_backlogShowWithChatEntry = true,
			epic_Chili_Pro_Console_changeFont = false,
			epic_Chili_Pro_Console_enableConsole = false,
			epic_Chili_Pro_Console_text_height_chat = 16,
			epic_Chili_Pro_Console_text_height_console = 16,
			["epic_Chili_Selections_&_CursorTip_v2_allowclickthrough"] = true,
			["epic_Chili_Selections_&_CursorTip_v2_fancySkinning"] = "panel_2100",
			["epic_Chili_Selections_&_CursorTip_v2_leftPadding"] = 6,
			["epic_Chili_Selections_&_CursorTip_v2_selection_opacity"] = 1,
			["epic_Chili_Selections_&_CursorTip_v2_tooltip_opacity"] = 0.79999995,
			["epic_Chili_Selections_&_CursorTip_v2_uniticon_size"] = 44,
			["epic_Chili_Share_menu_v1.24_automation_clanmerge"] = true,
			epic_Chili_Spectator_Panels_clanNameLengthCutoff = 20,
			epic_Chili_Spectator_Panels_enablePlayerPanel = true,
			epic_Chili_Spectator_Panels_enableSpectator = true,
			epic_Chili_Spectator_Panels_fancySkinning = "panel_1011",
			epic_Chili_Spectator_Panels_playerOpacity = 1,
			epic_Chili_Spectator_Panels_resourceOpacity = 1,
			["epic_Combo_Overhead/Free_Camera_(experimental)_zoomouttocenter"] = true,
			["epic_Combo_Overhead_/_Free_Camera_fov"] = 45,
			["epic_Combo_Overhead_/_Free_Camera_freemode"] = false,
			["epic_Combo_Overhead_/_Free_Camera_smoothness"] = 0.80000001,
			["epic_Combo_Overhead_/_Free_Camera_zoomouttocenter"] = true,
			epic_Context_Menu_shortNotation = false,
			epic_CustomFormations2_dotsize = 0.69999999,
			epic_CustomFormations2_drawmode_v2 = "both",
			epic_CustomFormations2_linewidth = 1,
			epic_Default_Group_Recall_Fix_timeoutlength = 0.2,
			["epic_Defense_Range_Zero-K_allyair"] = true,
			["epic_Defense_Range_Zero-K_allyground"] = true,
			["epic_Defense_Range_Zero-K_specground"] = false,
			["epic_Defense_Range_Zero-K_specnuke"] = false,
			epic_Display_Keys_2_enable = false,
			["epic_Double-Click_attack-move_2.0_enabled"] = true,
			["epic_Double-Click_attack-move_enabled"] = true,
			epic_HUD_Presets_interfacePreset = "default",
			epic_HUD_Presets_maintainDefaultUI = false,
			epic_HUD_Presets_minimapScreenSpace = 0.19,
			epic_HUD_Presets_setToDefault = false,
			epic_HUD_Presets_updateNewDefaults = false,
			epic_HealthBars_barScale = 2,
			epic_HealthBars_minReloadTime = 1,
			epic_HealthBars_unitMaxHeight = 3300,
			epic_HealthBars_unitPercentHeight = 1350,
			epic_HealthBars_unitTitleHeight = 900,
			epic_Keep_Target_keepTarget = false,
			epic_Lasso_Terraform_GUI_structure_altSelect = false,
			epic_Lasso_Terraform_GUI_structure_holdMouse = false,
			epic_Local_Team_Colors_colorSetting = "default",
			epic_Local_Team_Colors_matchColors = false,
			epic_Local_Team_Colors_simpleEnemyAllyTeam = "autoffa",
			epic_Mex_Placement_Handler_rounding = 1,
			epic_Mex_Placement_Handler_size = 40,
			epic_Misc_default_command_replacements_guard_facs = true,
			epic_Missile_Silo_Range_missile_silo_advanced = true,
			epic_News_Ticker_backgroundOpacity = 0.69999999,
			epic_News_Ticker_hideBar = false,
			epic_News_Ticker_useSounds = false,
			epic_Outline_Shader_v3_thickness = 3,
			epic_Save_Game_Menu_autosaveFrequency = 1,
			epic_Save_Game_Menu_enableautosave = false,
			epic_Selection_Hierarchy_selectionFilteringOnlyAltOption = true,
			["epic_Settings/Camera_Camera_Type"] = "Default",
			["epic_Settings/Graphics/Effects_Particle_density"] = 15500,
			["epic_Settings/Graphics/Map_Detail_Map_Brightness"] = 0.79999995,
			["epic_Settings/Graphics/Map_Detail_Shadow_detail_level"] = 4096,
			["epic_Settings/Graphics/Map_Detail_Shadows_cast_by"] = "1",
			["epic_Settings/Graphics/Map_Detail_Terrain_detail"] = 75,
			["epic_Settings/Graphics/Unit_Visibility_Draw_Distance"] = 1495,
			["epic_Settings/Graphics/Unit_Visibility_Icon_Distance"] = 81,
			["epic_Settings/HUD_Panels/Extras/HUD_Skin_Skin_Sets_(Requires_LuaUI_Reload)"] = "Evolved",
			["epic_Settings/HUD_Panels/Pause_Screen_Menu_pauses_in_SP"] = false,
			["epic_Settings/HUD_Panels/Pause_Screen_Menu_unpauses_in_SP"] = false,
			["epic_Settings/Misc_Show_Advanced_Settings"] = true,
			epic_Show_All_Commands_v2_showallcommandselection = "showallcommand",
			epic_Show_selected_unit_range_showselectedunitrange = true,
			epic_Showeco_and_Grid_Drawer_start_with_showeco = true,
			epic_Simple_Settings_Icon_Distance = 93,
			epic_Simple_Settings_always_show_mexes = true,
			epic_Simple_Settings_grabinput = true,
			epic_Simple_Settings_invertZoom = false,
			epic_Simple_Settings_minimapRight = false,
			epic_Simple_Settings_minimapScreenSpace = 0.19,
			epic_Simple_Settings_scrollSpeed = 200,
			epic_Simple_Settings_start_with_showeco = true,
			epic_Simple_Settings_useSelectionFilteringOption = true,
			epic_Simple_Settings_zoomSpeed = 40,
			epic_SmoothCam_camSpeed = 0,
			epic_SmoothCam_tiltZoom = 0.31999999,
			epic_Smooth_Scroll_smooth_mmb_scroll = true,
			epic_Startup_Info_and_Selector_hideTrainers = false,
			epic_Startup_Info_and_Selector_showModules = true,
			epic_Stereo3D_hidecursor = true,
			epic_UnitShapes_allyselectionlevel = "enabled",
			epic_UnitShapes_showallyplayercolours = false,
			epic_Unit_Start_State_amphriot_floattoggle = 1,
			epic_Unit_Start_State_athena_airstrafe1 = false,
			epic_Unit_Start_State_athena_constructor_buildpriority = 2,
			epic_Unit_Start_State_athena_personal_cloak_0 = true,
			epic_Unit_Start_State_athena_selection_rank = 2,
			epic_Unit_Start_State_bomberdisarm_firestate0 = 0,
			epic_Unit_Start_State_bomberdisarm_movestate1 = 0,
			epic_Unit_Start_State_bomberheavy_firestate0 = -1,
			epic_Unit_Start_State_bomberheavy_movestate1 = 0,
			epic_Unit_Start_State_bomberprec_firestate0 = 0,
			epic_Unit_Start_State_bomberprec_movestate1 = 0,
			epic_Unit_Start_State_bomberriot_firestate0 = 0,
			epic_Unit_Start_State_bomberriot_movestate1 = 0,
			epic_Unit_Start_State_cloaksnipe_firestate0 = -1,
			epic_Unit_Start_State_factoryamph_auto_assist = true,
			epic_Unit_Start_State_factorycloak_auto_assist = true,
			epic_Unit_Start_State_factorygunship_auto_assist = true,
			epic_Unit_Start_State_factoryhover_auto_assist = true,
			epic_Unit_Start_State_factoryjump_auto_assist = true,
			epic_Unit_Start_State_factoryplane_auto_assist = true,
			epic_Unit_Start_State_factoryplane_movestate1 = 0,
			epic_Unit_Start_State_factoryplane_repeat = true,
			epic_Unit_Start_State_factoryshield_auto_assist = true,
			epic_Unit_Start_State_factoryship_auto_assist = true,
			epic_Unit_Start_State_factoryspider_auto_assist = true,
			epic_Unit_Start_State_factorytank_auto_assist = true,
			epic_Unit_Start_State_factoryveh_auto_assist = true,
			epic_Unit_Start_State_planecon_airstrafe1 = true,
			epic_Unit_Start_State_planefighter_movestate1 = 0,
			epic_Unit_Start_State_planeheavyfighter_movestate1 = -1,
			epic_Unit_Start_State_planelightscout_movestate1 = 0,
			epic_Unit_Start_State_planelightscout_retreatpercent = 2,
			epic_Unit_Start_State_planescout_movestate1 = 0,
			epic_Unit_Start_State_planescout_retreatpercent = 2,
			epic_Unit_Start_State_planescout_tactical_ai_2 = false,
			epic_Unit_Start_State_staticmissilesilo_repeat = true,
			epic_Unit_Start_State_striderantiheavy_firestate0 = 0,
			epic_Unit_Start_State_striderantiheavy_movestate1 = 0,
			epic_Unit_Start_State_striderarty_firestate0 = 0,
			epic_Unit_Start_State_striderscorpion_firestate0 = 0,
			epic_Unit_Start_State_vehcapture_movestate1 = 0,
			epic_Unit_Start_State_vehcapture_tactical_ai_2 = false,
			epic_Unit_Start_State_vehheavyarty_movestate1 = -1,
			epic_Unit_Start_State_vehheavyarty_tactical_ai_2 = false,
			epic_Unit_Target_Command_Helper_circleDragThreshold = 15,
			epic_Vertical_Line_on_Radar_Dots_v2_enable_vertical_lines_air = "radar",
			epic_Vertical_Line_on_Radar_Dots_v2_enable_vertical_lines_ally = "never",
			epic_Chili_Minimap_radar_jammer_color = {
				[1] = 0.1,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			epic_Chili_Minimap_radar_radar2_color = {
				[1] = 0,
				[2] = 0,
				[3] = 1,
				[4] = 0,
			},
			epic_Chili_Minimap_radar_radar_color = {
				[1] = 0,
				[2] = 0,
				[3] = 1,
				[4] = 0,
			},
		},
		widgets = {},
	},
	["HUD Presets"] = {
		oldScreenHeight = 1080,
		oldScreenWidth = 1920,
	},
	["In-game Ignore"] = {},
	["Local Widgets Config"] = {
		localWidgets = true,
		localWidgetsFirst = false,
	},
	["Losses Counter "] = {
		[1] = 0.25989583,
		[2] = 0.09259259,
	},
	["Nuke Button Zero-K"] = {
		buttonXPer = 0.935,
		buttonYPer = 0.76499999,
	},
	["Persistent Build Height"] = {
		buildHeight = {
			energyfusion = -100,
			energygeo = -120,
			energypylon = -80,
			energysingu = -160,
			energysolar = 20,
			factoryjump = 0,
			factoryplane = 0,
			factoryshield = -20,
			shipheavyarty = -40,
			staticantinuke = -120,
			staticarty = 80,
			staticcon = -100,
			staticheavyarty = 260,
			staticheavyradar = 140,
			staticmex = -100,
			staticmissilesilo = -40,
			staticnuke = -40,
			staticradar = 80,
			staticrearm = 20,
			staticshield = -60,
			staticstorage = -120,
			subtacmissile = -160,
			turretaafar = 120,
			turretaaheavy = 120,
			turretaalaser = 140,
			turretemp = 20,
			turretheavylaser = 40,
			turretimpulse = 80,
			turretmissile = 60,
			turretriot = 80,
		},
	},
	["Persistent Build Spacing"] = {
		buildSpacing = {
			athena = 4,
			cloakjammer = 4,
			cloaksnipe = 4,
			energyfusion = 4,
			energygeo = 0,
			energypylon = 41,
			energysingu = 4,
			energysolar = 0,
			energywind = 3,
			factoryamph = 8,
			factorycloak = 8,
			factorygunship = 8,
			factoryhover = 8,
			factoryjump = 4,
			factoryplane = 8,
			factoryshield = 4,
			factoryship = 8,
			factoryspider = 8,
			factorytank = 8,
			factoryveh = 8,
			mahlazer = 4,
			raveparty = 4,
			shipheavyarty = 4,
			spiderskirm = 4,
			staticantinuke = 4,
			staticarty = 4,
			staticcon = 3,
			staticheavyarty = 4,
			staticheavyradar = 4,
			staticjammer = 4,
			staticmex = 4,
			staticmissilesilo = 4,
			staticnuke = 4,
			staticradar = 4,
			staticrearm = 3,
			staticshield = 5,
			staticstorage = 0,
			striderantiheavy = 4,
			striderarty = 4,
			striderbantha = 4,
			striderdante = 4,
			striderdetriment = 4,
			striderfunnelweb = 4,
			striderhub = 4,
			striderscorpion = 4,
			subtacmissile = 4,
			turretaaclose = 4,
			turretaafar = 4,
			turretaaflak = 4,
			turretaaheavy = 4,
			turretaalaser = 4,
			turretantiheavy = 4,
			turretemp = 4,
			turretgauss = 4,
			turretheavy = 4,
			turretheavylaser = 5,
			turretimpulse = 4,
			turretlaser = 4,
			turretmissile = 5,
			turretriot = 4,
			turrettorp = 4,
			zenith = 4,
		},
	},
	["Win Counter"] = {
		allyTeamCount = 3,
		count = 1,
		hasWins = false,
		dahn = {
			allyTeam = 0,
			wins = 0,
			wonLastGame = false,
		},
	},
}
