return {
	["date"]= 20130630, 
	["keybinds"]= {
		{"exitwindow", "Ctrl+Alt+Shift+escape"}, 
		{"crudesubmenu", "F10"}, 
		{"togglecammode", "Ctrl+Alt+Shift+F5"}, 
		{"toggleoverview", "numpad/"}, 
		{"edit_backspace", "Any+backspace"}, 
		{"edit_complete", "Any+tab"}, 
		{"edit_return", "Any+enter"}, 
		{"edit_escape", "Any+escape"}, 
		{"chatally", "Alt+enter"}, 
		{"chatswitchally", "Alt+enter"}, 
		{"chatall", "None"}, 
		{"chatswitchall", "None"}, 
		{"chatspec", "None"}, 
		{"chatswitchspec", "None"}, 
		{"chat", "enter"}, 
		{"pause", "pause"}, 
		{"crudemenu", "None"}, 
		{"exitwindow", "None"}, 
		{"quitforce", "None"}, 
		{"speedup", "Shift+Ctrl+Alt+pageup"}, 
		{"slowdown", "Shift+Ctrl+Alt+pagedown"}, 
		{"prevmenu", "None"}, 
		{"nextmenu", "None"}, 
		{"decguiopacity", "None"}, 
		{"incguiopacity", "None"}, 
		{"specteam 0", "1"}, 
		{"specteam 10", "Ctrl+1"}, 
		{"Group1", {"Any+1", "Any+Numpad1"}, 
		{"specteam 1", "2"}, 
		{"specteam 11", "Ctrl+2"}, 
		{"Group2", {"Any+2", "Any+Numpad2"}}, 
		{"specteam 2", "3"}, 
		{"specteam 12", "Ctrl+3"}, 
		{"Group3", {"Any+3", "Any+Numpad3"}}, 
		{"specteam 3", "4"}, 
		{"specteam 13", "Ctrl+4"}, 
		{"Group4", {"Any+4", "Any+Numpad4"}}, 
		{"specteam 4", "5"}, 
		{"specteam 14", "Ctrl+5"}, 
		{"Group5", {"Any+5", "Any+Numpad5"}}, 
		{"specteam 5", "6"}, 
		{"specteam 15", "Ctrl+6"}, 
		{"Group6", {"Any+6", "Any+Numpad6"}}, 
		{"specteam 6", "7"}, 
		{"specteam 16", "Ctrl+7"}, 
		{"Group7", {"Any+7", "Any+Numpad7"}}, 
		{"specteam 7", "8"}, 
		{"specteam 17", "Ctrl+8"}, 
		{"Group8", {"Any+8", "Any+Numpad8"}}, 
		{"specteam 8", "9"}, 
		{"specteam 18", "Ctrl+9"}, 
		{"Group9", {"Any+9", "Any+Numpad9"}}, 
		{"specteam 9", "0"}, 
		{"specteam 19", "Ctrl+0"}, 
		{"Group0", {"Any+0", "Any+Numpad0"}}, 
		{"buildfacing inc", "Any+'"}, 
		{"drawinmap", "\\"}, 
		{"clearmapmarks", "A+backspace"}, 
		{"buildfacing dec", "Any+\\"}, 
		{"attack", "n"}, 
		{"areaattack", "A+n"}, 
		{"repeat", "b"}, 
		{"priority", "C+6"}, 
		{"selfd", "A+C+S+d"}, 
		{"selectcomm", "d"}, 
		{"manualfire", "C+n"}, 
		{"oneclickwep", "q"}, 
		{"placebeacon", "None"}, 
		{"selectmissiles", "None"}, 
		{"reclaim", "j"}, 
		{"fight", "m"}, 
		{"forcestart", "Alt+f"}, 
		{"areaguard", "A+C+e"}, 
		{"gameinfo", "Ctrl+Alt+i"}, 
		{"wantcloak", "None"}, 
		{"togglelos", "F3"}, 
		{"loadunits", "None"}, 
		{"loadselected", "None"}, 
		{"rawmove", "None"}, 
		{"singlestep", "Alt+o"}, 
		{"patrol", "A+C+m"}, 
		{"groupclear", "Shift+q"}, 
		{"repair", "o"}, 
		{"stop", "delete"}, 
		{"stopproduction", "delete"}, 
		{"globalbuildcancel", "Alt+s"}, 
		{"unloadunits", "None"}, 
		{"pastetext", "Ctrl+v"}, 
		{"wait", "None"}, 
		{"guard", "e"}, 
		{"areamex", "A+C+l"}, 
		{"wantonoff", "None"}, 
		{"pushpull", "None"}, 
		{"buildspacing dec", "Any+."}, 
		{"buildspacing inc", "Any+/"}, 
		{"edit_delete", "Any+delete"}, 
		{"edit_prev_line", "Any+up"}, 
		{"moveforward", "None"}, 
		{"edit_next_line", "Any+down"}, 
		{"moveback", "None"}, 
		{"edit_end", "Alt+right"}, 
		{"edit_next_word", "Ctrl+right"}, 
		{"edit_next_char", "Any+right"}, 
		{"moveright", "None"}, 
		{"edit_home", "Alt+left"}, 
		{"edit_prev_word", "Ctrl+left"}, 
		{"edit_prev_char", "Any+left"}, 
		{"moveleft", "None"}, 
		{"increaseviewradius", "home"}, 
		{"edit_home", "Any+home"}, 
		{"decreaseviewradius", "end"}, 
		{"edit_end", "Any+end"}, 
		{"moveup", "None"}, 
		{"movedown", "None"}, 
		{"showelevation", "F6"}, 
		{"togglestatsgraph", "A+F1"}, 
		{"showpathtraversability", "F5"}, 
		{"lastmsgpos", "backspace"}, 
		{"showeco", "F4"}, 
		{"showmetalmap", "None"}, 
		{"hideinterfaceandcursor", "print"}, 
		{"NoSound", "Any+F6"}, 
		{"DynamicSky", "Any+F7"}, 
		{"savegame", "None"}, 
		{"createvideo", "None"}, 
		{"viewlobby", "F11"}, 
		{"luaui tweakgui", "C+F11"}, 
		{"movefast", "numpad*"}, 
		{"moveslow", "None"}, 
		{"epic_chili_widget_selector_widgetlist_2", "Alt+F11"}, 
		{"screenshot png", "None"}, 
		{"screenshot jpg", "None"}, 
		{"settargetcircle", "C+e"}, 
		{"resurrect", "C+l"}, 
		{"jump", "k"}, 
		{"select AllMap+_ClearSelection_SelectAll+", "Ctrl+a"}, 
		{"selectidlecon_all", "g"}, 
		{"selectidlecon", "Alt+g"}, 
		{"select PrevSelection+_Not_RelativeHealth_30+_ClearSelection_SelectAll+", "None"}, 
		{"select AllMap+_Not_Builder_Not_Building+_ClearSelection_SelectAll+", "None"}, 
		{"select AllMap+_NameContain_Raptor+_ClearSelection_SelectAll+", "None"}, 
		{"select PrevSelection+_Idle+_ClearSelection_SelectAll+", "None"}, 
		{"select AllMap+_Not_Builder_Not_Building_Not_Transport_Aircraft_Radar+_ClearSelection_SelectAll+", "None"}, 
		{"select AllMap+_Not_Builder_Not_Building_Transport_Aircraft+_ClearSelection_SelectAll+", "None"}, 
		{"select Visible+_InPrevSel+_ClearSelection_SelectAll+", "Ctrl+/"}, 
		{"select AllMap+_InPrevSel+_ClearSelection_SelectAll+", "Ctrl+."}, 
		{"epic_chili_integral_menu_tab_economy", "l"}, 
		{"epic_chili_integral_menu_tab_defence", "u"}, 
		{"epic_chili_integral_menu_tab_special", "y"}, 
		{"epic_chili_integral_menu_tab_factory", ";"}, 
		{"epic_chili_integral_menu_tab_units", "escape"}, 
		{"epic_chili_pro_console_enableconsole", "F8"}, 
		{"epic_chili_share_menu_v1.22_sharemenu", "tab"}, 
		{"epic_auto_group_removefromgroup", "`"}, 
		{"epic_building_starter_hotkey", "Any+,"}, 
		{"epic_chili_core_selector_select_factory_1", "numpad1"}, 
		{"epic_chili_core_selector_select_factory_2", "numpad2"}, 
		{"epic_chili_core_selector_select_factory_3", "numpad3"}, 
		{"epic_chili_core_selector_select_factory_4", "numpad4"}, 
		{"epic_chili_core_selector_select_factory_5", "numpad5"}, 
		{"epic_chili_share_menu_v1.24_sharemenu", "F1"}, 
		{"epic_persistent_build_height_hotkey_toggle", "Any+insert"}, 
		{"epic_persistent_build_height_hotkey_raise", "Any+up"}, 
		{"epic_persistent_build_height_hotkey_lower", "Any+down"}, 
		{"select AllMap+_InPrevSel_Not_Builder+_ClearSelection_SelectAll+", "None"}, 
		{"epic_chili_integral_menu_customgrid11", "j"}, 
		{"epic_chili_integral_menu_customgrid12", "l"}, 
		{"epic_chili_integral_menu_customgrid13", "u"}, 
		{"epic_chili_integral_menu_customgrid14", "y"}, 
		{"epic_chili_integral_menu_customgrid15", ";"}, 
		{"epic_chili_integral_menu_customgrid16", "["}, 
		{"epic_chili_integral_menu_customgrid21", "h"}, 
		{"epic_chili_integral_menu_customgrid22", "n"}, 
		{"epic_chili_integral_menu_customgrid23", "e"}, 
		{"epic_chili_integral_menu_customgrid24", "i"}, 
		{"epic_chili_integral_menu_customgrid25", "o"}, 
		{"epic_chili_integral_menu_customgrid26", "'"}, 
		{"epic_chili_integral_menu_customgrid31", "k"}, 
		{"epic_chili_integral_menu_customgrid32", "m"}, 
		{"epic_chili_integral_menu_customgrid33", ","}, 
		{"epic_chili_integral_menu_customgrid34", "."}, 
		{"epic_chili_integral_menu_customgrid35", "/"}, 
		{"epic_chili_integral_menu_customgrid36", "None"}, 
		{"epic_hide_interface_and_mouse_cursor_cursor_animated", "None"}, 
		{"canceltarget", "Ctrl+delete"}, 
		{"repeat 1", "Any+b"}, 
		{"repeat 0", "Any+b"}, 
		{"levelground", "None"}, 
		{"firestate 2", "pageup"}, 
		{"firestate 0", "pageup"}, 
		{"dontfireatradar 0", "C+pageup"}, 
		{"dontfireatradar 1", "C+pageup"}, 
		{"firestate", "end"}, 
		{"dontfireatradar", "insert"}, 
		{"luaui showhealthbars", "alt+f9"}, 
		{"showhealthbars", "alt+f9"}, 
		{"debug", "None"}, 
		{"debugcolvol", "None"}, 
		{"upgradecommstop", "None"}, 
		{"idlemode", "None"}, 
		{"sethaven", "None"}, 
		{"select AllMap++_ClearSelection_SelectAll+", "ctrl+a"}, 
		{"HideInterface", "None"}, 
	}, 
}