return {
	["date"]= 20130630, 
	["keybinds"]= {
		{"exitwindow", "Ctrl+Alt+Shift+escape"}, 
		{"crudesubmenu", "F10"}, 
		{"togglecammode", "Ctrl+Alt+Shift+F5"}, 
		{"edit_backspace", "Any+backspace"}, 
		{"edit_complete", "Any+tab"}, 
		{"edit_return", "Any+enter"}, 
		{"edit_escape", "Any+escape"}, 
		{"chatally", "Alt+enter"}, 
		{"chatswitchally", "Alt+enter"}, 
		{"chatall", "None"}, 
		{"chatswitchall", "None"}, 
		{"chatspec", "None"}, 
		{"chatswitchspec", "None"}, 
		{"chat", "enter"}, 
		{"pause", "pause"}, 
		{"crudemenu", "None"}, 
		{"exitwindow", "None"}, 
		{"quitforce", "None"}, 
		{"speedup", "Shift+Ctrl+Alt+pageup"}, 
		{"slowdown", "Shift+Ctrl+Alt+pagedown"}, 
		{"prevmenu", "None"}, 
		{"nextmenu", "None"}, 
		{"decguiopacity", "None"}, 
		{"incguiopacity", "None"}, 
		{"specteam 0", "1"}, 
		{"specteam 10", "Ctrl+1"}, 
		{"group1", "Any+1"}, 
		{"specteam 1", "2"}, 
		{"specteam 11", "Ctrl+2"}, 
		{"group2", "Any+2"}, 
		{"specteam 2", "3"}, 
		{"specteam 12", "Ctrl+3"}, 
		{"group3", "Any+3"}, 
		{"specteam 3", "4"}, 
		{"specteam 13", "Ctrl+4"}, 
		{"group4", "Any+4"}, 
		{"specteam 4", "5"}, 
		{"specteam 14", "Ctrl+5"}, 
		{"group5", "Any+5"}, 
		{"specteam 5", "6"}, 
		{"specteam 15", "Ctrl+6"}, 
		{"group6", "Any+6"}, 
		{"specteam 6", "7"}, 
		{"specteam 16", "Ctrl+7"}, 
		{"group7", "Any+7"}, 
		{"specteam 7", "8"}, 
		{"specteam 17", "Ctrl+8"}, 
		{"group8", "Any+8"}, 
		{"specteam 8", "9"}, 
		{"specteam 18", "Ctrl+9"}, 
		{"group9", "Any+9"}, 
		{"specteam 9", "0"}, 
		{"specteam 19", "Ctrl+0"}, 
		{"group0", "Any+0"}, 
		{"buildfacing inc", "Any+left"}, 
		{"drawinmap", "\\"}, 
		{"clearmapmarks", "A+\\"}, 
		{"buildfacing dec", "Any+right"}, 
		{"attack", "n"}, 
		{"areaattack", "A+n"}, 
		{"repeat", "b"}, 
		{"priority", "None"}, 
		{"selfd", "A+C+S+d"}, 
		{"selectcomm", "="}, 
		{"manualfire", "C+n"}, 
		{"oneclickwep", "."}, 
		{"placebeacon", "None"}, 
		{"selectmissiles", "None"}, 
		{"reclaim", "h"}, 
		{"fight", "m"}, 
		{"forcestart", "Alt+f"}, 
		{"areaguard", "e"}, 
		{"gameinfo", "Ctrl+Alt+i"}, 
		{"wantcloak", "None"}, 
		{"togglelos", "F3"}, 
		{"loadunits", "None"}, 
		{"loadselected", "None"}, 
		{"rawmove", "None"}, 
		{"singlestep", "Alt+o"}, 
		{"patrol", ","}, 
		{"groupclear", "Shift+q"}, 
		{"repair", "A+j"}, 
		{"stop", "delete"}, 
		{"stopproduction", "C+delete"}, 
		{"globalbuildcancel", "Alt+s"}, 
		{"unloadunits", "None"}, 
		{"pastetext", "Ctrl+v"}, 
		{"wait", "A+delete"}, 
		{"guard", "None"}, 
		{"areamex", "j"}, 
		{"wantonoff", "C+home"}, 
		{"pushpull", "None"}, 
		{"buildspacing dec", "Any+."}, 
		{"buildspacing inc", "Any+/"}, 
		{"edit_delete", "Any+delete"}, 
		{"edit_prev_line", "Any+up"}, 
		{"moveforward", "None"}, 
		{"edit_next_line", "Any+down"}, 
		{"moveback", "None"}, 
		{"edit_end", "Alt+right"}, 
		{"edit_next_word", "Ctrl+right"}, 
		{"edit_next_char", "Any+right"}, 
		{"moveright", "None"}, 
		{"edit_home", "Alt+left"}, 
		{"edit_prev_word", "Ctrl+left"}, 
		{"edit_prev_char", "Any+left"}, 
		{"moveleft", "None"}, 
		{"increaseviewradius", "home"}, 
		{"edit_home", "Any+home"}, 
		{"decreaseviewradius", "end"}, 
		{"edit_end", "Any+end"}, 
		{"moveup", "None"}, 
		{"movedown", "None"}, 
		{"showelevation", "F6"}, 
		{"togglestatsgraph", "A+F1"}, 
		{"showpathtraversability", "F5"}, 
		{"lastmsgpos", "f12"}, 
		{"showeco", "F4"}, 
		{"showmetalmap", "None"}, 
		{"hideinterfaceandcursor", "C+S+f3"}, 
		{"NoSound", "Any+F6"}, 
		{"DynamicSky", "Any+F7"}, 
		{"savegame", "None"}, 
		{"createvideo", "None"}, 
		{"viewlobby", "F11"}, 
		{"luaui tweakgui", "A+f3"}, 
		{"movefast", "None"}, 
		{"moveslow", "None"}, 
		{"epic_chili_widget_selector_widgetlist_2", "Alt+F11"}, 
		{"screenshot png", "None"}, 
		{"screenshot jpg", "None"}, 
		{"settargetcircle", "C+e"}, 
		{"resurrect", "A+h"}, 
		{"jump", "k"}, 
		{"select AllMap+_ClearSelection_SelectAll+", "Ctrl+a"}, 
		{"selectidlecon_all", "g"}, 
		{"selectidlecon", "p"}, 
		{"select PrevSelection+_Not_RelativeHealth_30+_ClearSelection_SelectAll+", "A+["}, 
		{"select AllMap+_Not_Builder_Not_Building+_ClearSelection_SelectAll+", "None"}, 
		{"select AllMap+_NameContain_Raptor+_ClearSelection_SelectAll+", "None"}, 
		{"select PrevSelection+_Idle+_ClearSelection_SelectAll+", "None"}, 
		{"select AllMap+_Not_Builder_Not_Building_Not_Transport_Aircraft_Radar+_ClearSelection_SelectAll+", "-"}, 
		{"select AllMap+_Not_Builder_Not_Building_Transport_Aircraft+_ClearSelection_SelectAll+", "None"}, 
		{"select Visible+_InPrevSel+_ClearSelection_SelectAll+", "/"}, 
		{"select AllMap+_InPrevSel+_ClearSelection_SelectAll+", "C+/"}, 
		{"epic_chili_integral_menu_tab_economy", "l"}, 
		{"epic_chili_integral_menu_tab_defence", "u"}, 
		{"epic_chili_integral_menu_tab_special", "y"}, 
		{"epic_chili_integral_menu_tab_factory", ";"}, 
		{"epic_chili_integral_menu_tab_units", "backspace"}, 
		{"epic_chili_pro_console_enableconsole", "F8"}, 
		{"epic_chili_share_menu_v1.22_sharemenu", "tab"}, 
		{"epic_auto_group_removefromgroup", "`"}, 
		{"epic_building_starter_hotkey", "Any+-"}, 
		{"epic_chili_core_selector_select_factory_1", "f7"}, 
		{"epic_chili_core_selector_select_factory_2", "f8"}, 
		{"epic_chili_core_selector_select_factory_3", "f9"}, 
		{"epic_chili_core_selector_select_factory_4", "None"}, 
		{"epic_chili_core_selector_select_factory_5", "None"}, 
		{"epic_chili_share_menu_v1.24_sharemenu", "F1"}, 
		{"epic_persistent_build_height_hotkey_toggle", "None"}, 
		{"epic_persistent_build_height_hotkey_raise", "None"}, 
		{"epic_persistent_build_height_hotkey_lower", "None"}, 
		{"select AllMap+_InPrevSel_Not_Builder+_ClearSelection_SelectAll+", "A+C+/"}, 
		{"epic_chili_integral_menu_customgrid11", "j"}, 
		{"epic_chili_integral_menu_customgrid12", "l"}, 
		{"epic_chili_integral_menu_customgrid13", "u"}, 
		{"epic_chili_integral_menu_customgrid14", "y"}, 
		{"epic_chili_integral_menu_customgrid15", ";"}, 
		{"epic_chili_integral_menu_customgrid16", "["}, 
		{"epic_chili_integral_menu_customgrid21", "h"}, 
		{"epic_chili_integral_menu_customgrid22", "n"}, 
		{"epic_chili_integral_menu_customgrid23", "e"}, 
		{"epic_chili_integral_menu_customgrid24", "i"}, 
		{"epic_chili_integral_menu_customgrid25", "o"}, 
		{"epic_chili_integral_menu_customgrid26", "'"}, 
		{"epic_chili_integral_menu_customgrid31", "k"}, 
		{"epic_chili_integral_menu_customgrid32", "m"}, 
		{"epic_chili_integral_menu_customgrid33", ","}, 
		{"epic_chili_integral_menu_customgrid34", "."}, 
		{"epic_chili_integral_menu_customgrid35", "/"}, 
		{"epic_chili_integral_menu_customgrid36", "None"}, 
		{"epic_hide_interface_and_mouse_cursor_cursor_animated", "None"}, 
		{"canceltarget", "Ctrl+delete"}, 
		{"repeat 1", "None"}, 
		{"repeat 0", "None"}, 
		{"levelground", "down"}, 
		{"firestate 2", "pageup"}, 
		{"firestate 0", "pagedown"}, 
		{"dontfireatradar 0", "None"}, 
		{"dontfireatradar 1", "None"}, 
		{"firestate", "None"}, 
		{"dontfireatradar", "up"}, 
		{"luaui showhealthbars", "alt+f9"}, 
		{"showhealthbars", "alt+f9"}, 
		{"debug", "None"}, 
		{"debugcolvol", "None"}, 
		{"upgradecommstop", "C+q"}, 
		{"idlemode", "up"}, 
		{"sethaven", "A+x"}, 
		{"select AllMap++_ClearSelection_SelectAll+", "ctrl+a"}, 
		{"luaui reload", "A+C+S+f3"}, 
		{"settarget", "None"}, 
		{"cancelfirezone", "None"}, 
		{"find_pad", "None"}, 
		{"epic_auto_group_4_removefromgroup", "`"}, 
		{"floatstate", "None"}, 
		{"miscpriority", "None"}, 
		{"movestate", "home"}, 
		{"epic_chili_core_selector_select_factory_6", "None"}, 
		{"select PrevSelection+_Not_RelativeHealth_60+_ClearSelection_SelectAll+", "A+]"}, 
		{"select PrevSelection+_RelativeHealth_30+_ClearSelection_SelectAll+", "C+["}, 
		{"select PrevSelection+_RelativeHealth_60+_ClearSelection_SelectAll+", "C+]"}, 
		{"select PrevSelection+_Builder+_ClearSelection_SelectAll+", "A+g"}, 
		{"floatstate 2", "A+up"}, 
		{"floatstate 0", "down"}, 
		{"wantonoff 1", "home"}, 
		{"wantonoff 0", "end"}, 
		{"priority 2", "numpad+"}, 
		{"priority 0", "numpad-"}, 
		{"priority 1", "numpad*"}, 
		{"floatstate 1", "up"}, 
		{"epic_hotkeys/misc_choose_commander_type", "f12"}, 
		{"airstrafe", "end"}, 
		{"upgradecomm", "q"}, 
		{"epic_chili_global_commands_simplifiedteamcolor", "f9"}, 
		{"epic_settings/misc_toggle_new_widget_profiler", "C+S+f11"}, 
		{"epic_lasso_terraform_gui_raise_hotkey_5", "up"}, 
		{"epic_lasso_terraform_gui_level_hotkey_5", "down"}, 
		{"epic_combo_overhead/free_camera_(experimental)_overviewmode", "tab"}, 
		{"epic_combo_overhead/free_camera_(experimental)_follow", "None"}, 
		{"epic_combo_overhead/free_camera_(experimental)_trackmode", "None"}, 
		{"epic_combo_overhead/free_camera_(experimental)_thirdpersontrack", "None"}, 
		{"add_llt_action", "j"}, 
		{"preventoverkill 0", "A+C+r"}, 
		{"preventoverkill 1", "A+C+w"}, 
		{"raiseground", "up"}, 
		{"epic_icon_zoom_transition_iconmodehotkey", "Alt+I"}, 
		{"epic_chili_pro_console2_enableconsole", "A+f12"}, 
		{"epic_combo_overhead_/_free_camera_overviewmode", "tab"}, 
		{"epic_combo_overhead_/_free_camera_follow", "None"}, 
		{"epic_combo_overhead_/_free_camera_trackmode", "None"}, 
		{"epic_combo_overhead_/_free_camera_thirdpersontrack", "None"}, 
		{"toggleoverview", "None"}, 
		{"HideInterface", "None"}, 
	}, 
}